### ISSUE TITLE
Set Up The VM

### ISSUE THREAD

**Issue by reaper10567** [reaper10567/344-Web-Engineering#11]
Configure IIS and get git installed on the VM

**Comment by mikairi** [comment]
It's up and running http://vm344f.se.rit.edu/app

Currently you have to compile and publish from your local machine though, since it requires VS2015. Then copy the published folder to the VM replacing the current one. This shouldn't be a problem though if we just have 3 releases - 3 deployments. We can easily zip up the compiled files and upload to Github as a release, then download, unpack and deploy on the VM.
